# Generated by Django 2.2.17 on 2021-01-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_auto_20210108_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
